spring:
  application:
    name: battle-results-data-service
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          fetch_size: 400
        generate_statistics: true
        format_sql: true
        default_schema: public

server:
  port: 9082

springdoc:
  swagger-ui:
    use-root-path: true
