spring:
  application:
    name: players-stats-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          fetch_size: 400
        generate_statistics: true
        format_sql: true
        default_schema: player_stats
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1
    schemas: player_stats
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: password

server:
  port: 9081

springdoc:
  swagger-ui:
    use-root-path: true
